package com.br.RpgStory.main;
import java.io.IOException;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.br.RpgStory.user.User;
import com.br.RpgStory.user.UserDAO;
public class ApplicationMain_UserLogin extends HttpServlet {
	
	private User user;
	private UserDAO dao;
	private String userLogin = "";
	private String userPass  = "";
	private String sqlQuery;
	private Connection conection;
    PreparedStatement sendSQLogin;
    ResultSet rs;
    String login;
    String password;
	
	/* Servlet UserLogin */
	protected void doPost(HttpServletRequest req, HttpServletResponse resp)
			throws ServletException, IOException {

		/* Login & senha do usuário */
		login    = req.getParameter("GetName");
		password = req.getParameter("GetPassword");

		/* Cria uma instância do objeto usuário */
		user = new User();
		
		/* Passa o nome do usuário e sua senha */
		user.setUser(login);
		user.setPassword(password);

		/* Cria um instância do objeto DAO */
		UserDAO dao = new UserDAO();

		try {
			/* seleciona o usuário e senha cadastrados no banco de dados */
			sqlQuery  = "select nome,senha from login where nome = ? and senha = ?";
			userLogin = "";
			userPass  = "";

			/* Conecta ao banco de dados */
			conection = dao.getConnect();

			/*
			 * Creates a PreparedStatement object for sending parameterized SQL
			 * statements to the database.
			 */
			sendSQLogin = conection.prepareStatement(sqlQuery);
			
			/* Sets the designated parameter to the given Java String value */
			sendSQLogin.setString(1, user.getUser());
			sendSQLogin.setString(2, user.getPassword());
			
			/*Executes the SQL query in this PreparedStatement object and*/
			/*returns the ResultSet object generated by the query.*/	
			rs = sendSQLogin.executeQuery();
			
			/*Moves the cursor forward one row from its current position*/
			while(rs.next()){
				/*Retrieves the value of the designated column in the current row of this ResultSet object*/
				userLogin = rs.getString("nome");
				userPass  = rs.getString("senha");
			}
			
			/*Passa o usuário e a senha*/
			dao.login(userLogin, userPass, user, req, resp);
			
			/*Fecha o Objeto ResultSet,Connection & PreparedStatement */
			rs.close();
			conection.close();
			sendSQLogin.close();
		
		} catch (SQLException exception) {
			throw new RuntimeException(exception);
		}

	}

}
